### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by IDKYamHere** [ashus3868/RasaCustomerService#1]
When I run python Voice_bot.py I am getting the error :

Bot says,  Hello! I am calling from Innovate Yourself. How may I assist you?
saved
Traceback (most recent call last):
  File "Voice_bot.py", line 27, in <module>
    subprocess.call(['mpg321', "welcome.mp3", '--play-and-exit'])
  File "C:\Users\siddu\anaconda3\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\siddu\anaconda3\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\siddu\anaconda3\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

In the rasa run -m models .... console it returns :
Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled

I am running the project on windows, rasa=1.8

**Comment by ashus3868** [comment]
You have to install mpg321 for that

**Comment by IDKYamHere** [comment]
I already had mpg321 installed. It is unable to call the welcome.mp3 file even though the mp3 file is present in the directory. Is it a Windows error that I'm tackling?

**Comment by ashus3868** [comment]
https://pypi.org/project/playsound/

Check this link to play the recorded sound using playsound instead or using
subprocess

**Comment by IDKYamHere** [comment]
Thank you very much. It worked! :')
